route:
  group_by: [ alertname ]
  receiver: 'mail' # default receiver
  repeat_interval: 24h
  routes:
    - receiver: 'mail'
      repeat_interval: 12h
      matchers:
        - severity="medium"

    - receiver: 'mail'
      repeat_interval: 4h
      matchers:
        - severity="high"


receivers:
  - name: 'mail'
    email_configs:
      - smarthost: 'yourmailhost.com:465'
        auth_username: 'yourmail@yourmailhost.com'
        auth_password: "your mail password"
        from: 'yourmail@yourmailhost.com'
        to: 'someonesmail@yourmailhost.com'
        require_tls: false